from .interoperable_target import InteroperableTarget


class IEC_61850_7_420(InteroperableTarget):
    def __init__(self, **kwargs):
        super(IEC_61850_7_420, self).__init__(**kwargs)

    def read_permit_service(self):
        return True if self.target_mapping['DCTE.RtnSrvAuto'] and self.target_mapping['DCTE.RtnSrvAuth'] else False

    def prep_write_permit_service(self, value):
        return {'DCTE.RtnSrvAuto': value, 'DCTE.RtnSrvAuth': value}
    
    MAPPING = {
        'Nameplate Active Power (unity)': ['DGEN.WMaxRtg'],
        'Nameplate Active Power (over-excited)':  [ 'DGEN.WGnOvPFRtg'],
        'Nameplate Power Factor (over-excited)':  [ 'DGEN.OvPFRtg'],
        'Nameplate Active Power (under-excited)':  [ 'DGEN.WGnUnPFRtg'],
        'Nameplate Power Factor (under-excited)':  [ 'DGEN.UnPFRtg'],
        'Nameplate Apparent Power (Max)':  [ 'DGEN.VAMaxRtg'],
        'Nameplate Normal (operating category)':  [ 'DGEN.Ieee1547Cat1'],
        'Nameplate Abnormal (operating category)':  [ 'DGEN.Ieee1547Cat2'],
        'Nameplate Reactive Power (Max Injected)':  [ 'DGEN.VarMaxSupRtg'],
        'Nameplate Reactive Power (Max Absorbed)':  [ 'DGEN.VarMaxAbgRtg'],
        'Nameplate Active Power (Max Charge)':  [ 'DSTO.WChaUnPFRtg'],
        'Nameplate Apparent Power (Max Charge)':  [ 'DSTO.VAMaxChaRtg'],
        'Nameplate Voltage AC (nominal)':  [ 'DECP.VRef'],
        'Nameplate Voltage AC (max)':  [ 'DGEN.VMaxRtg'],
        'Nameplate Voltage AC (min)':  [ 'DGEN.VMinRtg'],
        'Nameplate Supported Control Mode Functions':  [ 'DVRT', 'DFRT', 'DFWP', 'DWLM', 'DVWC', 'DFWC', 'DVAR', 'DFPF',
                                                         'DVVC', 'DWVR'],
        'Nameplate Reactive Susceptance':  [ 'DGEN.SuscRtg'],
        'Nameplate Manufacturer':  [ 'LPHD.PhyNam.vendor'],
        'Nameplate Model':  [ 'LPHD.PhyNam.model'],
        'Nameplate Serial Number':  [ 'LPHD.PhyNam.serNum'],
        'Nameplate Version':  [ 'LPHD.PhyNam.swRev'],
        'Nameplate Storage Capacity':  [ 'DSTO.WhRtg'],
        'Configuration Active Power (unity)':  [ 'DGEN.Wmax'],
        'Configuration Active Power (over-excited)':  [ 'DGEN.WGnOvPFRtg'],
        'Configuration Power Factor (over-excited)':  [ 'DGEN.OvPFRtg'],
        'Configuration Active Power (under-excited)':  [ 'DGEN.WGnUnPFRtg'],
        'Configuration Power Factor (under-excited)':  [ 'DGEN.UnPFRtg'],
        'Configuration Apparent Power (Max)':  [ 'DGEN.VAMax'],
        'Configuration Normal (operating category)':  [ 'DGEN.RegCap'],
        'Configuration Abnormal (operating category)':  [ 'DGEN.RegCap'],
        'Configuration Reactive Power (Max Injected)':  [ 'DGEN.VarMaxSupRtg'],
        'Configuration Reactive Power (Max Absorbed)':  [ 'DGEN.VarMaxAbgRtg'],
        'Configuration Active Power (Max Charge)':  [ 'DSTO.WChaUnPFRtg'],
        'Configuration Apparent Power (Max Charge)':  [ 'DSTO.VAMaxChaRtg'],
        'Configuration Voltage AC (nominal)':  [ 'DECP.VRef'],
        'Configuration Voltage AC (max)':  [ 'DGEN.Vmax'],
        'Configuration Voltage AC (min)':  [ 'DGEN.Vmin'],
        'Configuration Supported Control Mode Functions':  ['DVRT', 'DFRT', 'DFWP', 'DWLM', 'DVWC', 'DFWC', 'DVAR',
                                                            'DFPF', 'DVVC', 'DWVR'],
        'Configuration Reactive Susceptance':  [ 'DGEN.SuscRtg'],
        'Configuration Manufacturer':  [ 'LPHD.PhyNam.vendor'],
        'Configuration Model':  [ 'LPHD.PhyNam.model'],
        'Configuration Serial Number':  [ 'LPHD.PhyNam.serNum'],
        'Configuration Version':  [ 'LPHD.PhyNam.swRev'],
        'Configuration Storage Capacity':  [ 'DSTO.WhRtg'],
        'Monitoring Active Power': ['DECP.MMXU.TotW'],
        'Monitoring Reactive Power':  [ 'DECP.MMXU.TotVAr'],
        'Monitoring Voltage(s)':  [ 'DECP.MMXU.PhV.phsA.mag, DECP.MMXU.PhV.phsB.mag, DECP.MMXU.PhV.phsC.mag'],
        'Monitoring Frequency':  [ 'DECP.MMXU.Hz'],
        'Monitoring Operation State':  [ 'DGEN.DERState'],
        'Monitoring Connection Status':  [ 'DSTO.DERState.1'],
        'Monitoring Alarm Status':  [ 'CALH.GrAlm'],
        'Monitoring Operation SoC':  [ 'DSTO.SocUsePct'],
        'Constant PF Enable':  [ 'DFPF.ModEna'],
        'Constant PF Injection/Absorption setting':  [ 'DFPF.PFGnTgt, DFPF.PFLodTgt'],
        'Constant PF Excitation setting':  [ 'DFPF.PFExtSet'],
        'Volt-VAR Enable':  [ 'DVVR.ModEna'],
        'Volt-VAR Vref ':  [ 'DECP.VRef'],
        'Volt-VAR Autonomous Vref Adjustment enable':  [ 'DECP.VRefOfs'],
        'Volt-VAR Vref Adjustment Time Constant':  [ 'DVVR.VRefTmms'],
        'Volt-VAR V/Q Curve Points':  [ 'DVVR.VVArCrv'],
        'Volt-VAR Open Loop Response Time':  [ 'DVVR.OpnLoopMax'],
        'Watt-VAR Enable':  [ 'DWVR.ModEna'],
        'Watt-VAR P/Q Curve Points':  [ 'DWVR.WVArCrv'],
        'Constant VAR Enable':  [ 'DVAR.ModEna'],
        'Constant VAR VAR Setting':  [ 'DVAR.VArTgt'],
        'Volt-Watt Enable':  [ 'DVWC.ModEna'],
        'Volt-Watt V/P Curve Points':  [ 'DVWC.VWCrv'],
        'Volt-Watt Open Loop Response Time':  [ 'DVWC.OpnLoopMax'],
        'Voltage Trip HV Trip Curve Points':  [ 'DHVT.TrZnSt, PTOV.TmVCrv'],
        'Voltage Trip LV Trip Curve Points':  [ 'DLVT.TrZnSt, PTUV.TmVCrv'],
        'Momentary Cessation HV Trip Curve Points':  [ 'DHVT.CeaZnSt, PTOV.TmVCrv'],
        'Momentary Cessation LV Trip Curve Points':  [ 'DLVT.CeaZnSt, PTUV.TmVCrv'],
        'Frequency Trip HV Trip Curve Points':  [ 'DHFT.TrZnSt, PTOF.StrVal'],
        'Frequency Trip LV Trip Curve Points':  [ 'DLFT.TrZnSt, PTUF.StrVal'],
        'Frequency-Watt dbof':  [ 'DHFW.HzStr'],
        'Frequency-Watt dbuf':  [ 'DLFW.HzStr'],
        'Frequency-Watt kof':  [ 'DHFW.WGra'],
        'Frequency-Watt kuf':  [ 'DLFW.WGra'],
        'Frequency-Watt Open Loop Response Time':  [ 'DHFW.OpnLoopMax, DLFW.OpnLoopMax'],
        'Enter Service Permit service': ['DCTE.RtnSrvAuto, DCTE.RtnSrvAuth'],
        'Enter Service ES Voltage High':  [ 'DCTE.VHiLim'],
        'Enter Service ES Voltage Low':  [ 'DCTE.VLoLim'],
        'Enter Service ES Frequency High':  [ 'DCTE.HzHiLim'],
        'Enter Service ES Frequency Low':  [ 'DCTE.HzLoLim'],
        'Enter Service ES Delay':  [ 'DCTE.RtnSrvDlyTim'],
        'Enter Service ES Randomized Delay':  [ 'DCTE.RtnSrvDlyTim'],
        'Enter Service ES Ramp Time':  [ 'DCTE.RtnSrvRmpTim'],
        'Limit Watt Enable': [ 'DWMX.ModEna, DWMN.ModEna'],
        'Limit Watt Watt Setting': 'DWMX.LimW, DWMN.LimW'
    }
